version: "3"

services: 
  
  ### User Service ###
  user:
    build: "./user"
    container_name: user-service
    ports: 
      - "9091:9090"

  user-db:
    image: mariadb
    container_name: user-db
    restart: always
    ports: 
      - "33061:3306"
    volumes:
      - ./db/user-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret

  ### Product Service ###
  product:
    build: "./product"
    ports:
      - "9092:9090"

  product-db:
    image: mariadb
    container_name: product-db
    restart: always
    ports: 
      - "33062:3306"
    volumes:
      - ./db/product-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret

  ### Order Service ###
  order:
    build: "./order"
    ports:
      - "9093:9090"

  order-db:
    image: mariadb
    container_name: order-db
    restart: always
    ports: 
      - "33063:3306"
    volumes:
      - ./db/order-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret

  ### RabbitMQ ###
  # docker run -d --hostname my-rabbit --name some-rabbit -p 15672:15672 -p 5672:5672 rabbitmq:3-management
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: my-rabbit
    ports: 
      - 15672:15672
      - 5672:5672
    restart: always

  ### Nginx ###
  nginx:
    image: nginx:latest
    container_name: microservices_nginx
    ports: 
      - "80:80"
    volumes: 
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    depends_on: 
      - user
      - product
      - order