version: "3"

services: 
  
  ### User Service ###
  user:
    build: "./user"
    container_name: user-service
    ports: 
      - "9091:9090"
    depends_on: 
      - user-db

  user-db:
    image: mariadb
    container_name: user-db
    ports: 
      - "33061:3306"
    volumes:
      - ./db/user-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

  ### Product Service ###
  product:
    build: "./product"
    container_name: product-service
    ports:
      - "9092:9090"
    depends_on: 
      - product-db

  product-db:
    image: mariadb
    container_name: product-db
    ports: 
      - "33062:3306"
    volumes:
      - ./db/product-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

  ### Order Service ###
  order:
    build: "./order"
    container_name: order-service
    ports:
      - "9093:9090"
    depends_on: 
      - order-db

  order-db:
    image: mariadb
    container_name: order-db
    ports: 
      - "33063:3306"
    volumes:
      - ./db/order-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

  ### RabbitMQ ###
  # docker run -d --hostname my-rabbit --name some-rabbit -p 15672:15672 -p 5672:5672 rabbitmq:3-management
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: my-rabbit
    ports: 
      - 15672:15672
      - 5672:5672

  ### Nginx ###
  server:
    image: nginx:latest
    container_name: server
    ports: 
      - "8080:80"
    volumes: 
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    depends_on: 
      - user
      - product
      - order