version: "3"

services: 
  
  ### User Service ###
  user-service:
    build: "./user"
    container_name: user-service
    ports: 
      - "9091:9090"

  user-db:
    image: mariadb
    container_name: user-db
    restart: always
    ports: 
      - "33061:3306"
    volumes:
      - ./db/user-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret

  ### Product Service ###
  product-service:
    build: "./product"
    ports:
      - "9092:9090"

  product-db:
    image: mariadb
    container_name: product-db
    restart: always
    ports: 
      - "33062:3306"
    volumes:
      - ./db/product-db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret


  ### Nginx ###
  nginx:
    image: nginx:latest
    container_name: microservices_nginx
    ports: 
      - "80:80"
    volumes: 
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    depends_on: 
      - user-service